### PR TITLE
[FIX] maintainer-tools: Fix up in requirements bzr version 2.6 replaced for 2.7

### PR DESCRIPTION
**Pull request by JesusZapata**
Referring to https://github.com/Vauxoo/maintainer-tools/issues/13

image

### CODE REVIEW

**Comment by JesusZapata** [comment]
Travis is red because  flake8
```bash
[pbr] Generating ChangeLog
running flake8
tools/autopep8_extended.py:446:1: E305 expected 2 blank lines after class or function definition, found 1
tools/rename.py:27:1: E305 expected 2 blank lines after class or function definition, found 1
tools/oca_projects.py:149:1: E305 expected 2 blank lines after class or function definition, found 1
tools/tx_pull.py:116:1: E305 expected 2 blank lines after class or function definition, found 1
tools/oca_sync_users.py:41:1: E305 expected 2 blank lines after class or function definition, found 1
```
This is an isolated case to this PR!

**Comment by JesusZapata** [comment]
@moylop260 
What do you think about this PR?

**Comment by moylop260** [comment]
Thank you,
Could you propagate this patch to OCA too, please?

**Comment by moylop260** [comment]
And 10.0, 9.0 and 8.0 branches of vx

**Pull request merged**
